Refactor search builder
Stuyk/vitepress-plugin-simple-search pull request #21
Opened 2023-03-26 22:57 UTC by Tijawk

- upgrade dependencies
- remove options.ts. Options are merge in index.ts directly.
- remove baseSrc, docsPath and partialsToIgnore options.
- refactor searchBuilder to use VITEPRESS_CONFIG.pages
- rename preambuleTransformer to dataTransformer
- rename FileSearchData type to SearchData
- add DataTransformer and Options type files
- move search logic to useSimpleSearch to allow create custom Search.vue component
- move styles in assets/simpleSearch.css
- remove vue-tsc and add vite-plugin-dts to build .d.ts files
- update README.md

2023-03-28 12:17 UTC, Stuyk commented
Is this ready for review now?

2023-03-29 17:24 UTC, Tijawk commented
@Stuyk  I will add some unit tests and I'm taking a look on minisearch package for the search engine. Do you agree to let me use this package instead of custom search engine ?

https://www.npmjs.com/package/minisearch

2023-03-30 21:06 UTC, Stuyk commented
@Tijawk I think it's fine to replace the search; the implementation I put in was enough for my needs. :)

2023-04-02 22:44 UTC, Tijawk commented
@Stuyk You can take a quick look on my PR. 

If it's ok, I will rebase commits to have a more readable git history and make it ready to final review

2023-04-03 19:38 UTC, Stuyk requested changes
I had quite a few issues on my side; but after a little bit of work I did manage to get it working. Here's what I had to change to make it compatible.

I have no idea why but the Map type was just giving out tons of errors / issues.

Replacing with an Object seemed to have resolved all of it.

2023-04-03 19:38 UTC, Stuyk commented on src/index.ts
> +        return `export default ${JSON.stringify({
This has trouble being stringified for some reason. I was able to resolve this by doing a traditional key pair object instead.

See the relevant function for the comment.

2023-04-03 19:38 UTC, Stuyk commented on src/dataBuilder.ts
> +  const indexedData = new Map<string, IndexedData>();
This map causes issues, not sure why but here's the solution that resolved it.

```ts
  const { pages } = (global as any).VITEPRESS_CONFIG as VPConfig;
  const indexedData: { [key: string]: IndexedData } = {};
  const promises = [];
  for (let page of pages) {
    const promise = new Promise(async (resolve: Function) => {
      const searchData = await extractPageData(page, options);
      indexedData[searchData.id] = searchData;
      resolve();
    });

    promises.push(promise);
  }

  await Promise.all(promises);
  ```

2023-04-03 19:38 UTC, Stuyk commented on src/composables/useSimpleSearch.ts
> +      await simpleSearch.value.addAllAsync(
Issue with value.values()

Instead need to use Object reflection.

```ts
const searchableData = Object.values(indexedData.value);
await simpleSearch.value.addAllAsync(searchableData);
 ```

2023-04-03 19:38 UTC, Stuyk commented on vite-env.d.ts
> +  const indexedData: Map<string, IndexedData>;
```ts
{ [key: string]: IndexedData }
```

2023-04-03 19:38 UTC, Stuyk commented on src/composables/useSimpleSearch.ts
> +  const indexedData = ref<Map<string, IndexedData>>(new Map());
```
{ [key: string]: IndexedData }
```

2023-04-04 09:04 UTC, Tijawk commented on src/__tests__/searchBuilder.test.ts
> +  test('cleanupFix should remove .md extension from file path', () => {
typo: cleanupFix => cleanupLink

2023-04-04 09:04 UTC, Tijawk commented on src/__tests__/searchBuilder.test.ts
> +  test('extractSearchData should return an object with the correct properties', async () => {
typo: extractSearchData => build

2023-04-04 09:04 UTC, Tijawk commented on src/__tests__/useSimpleSearch.test.ts
> +  };
Convert Map to Object

2023-04-04 09:04 UTC, Tijawk commented on src/index.ts
> + * @param {UserOptions} options
UserOptions => Partial\<Options\>

2023-04-04 09:04 UTC, Tijawk commented on src/index.ts
> +        return `export default ${JSON.stringify({
Ok, it's logic, `JSON.stringify` does not know how to stringify a Map instance.  It's strange that I don't have any issue about that during npm build on my side.

I will fix that with a simple `Object` as you suggest

2023-04-08 14:52 UTC, Stuyk commented
Works pretty well overall; but I only have a handful of issues with the changes.

1. Variables are displayed from front matter and are not parsed.

Before:
![](https://i.imgur.com/AS6Zyg6.png)

After:
![](https://i.imgur.com/3DCL3Qc.png)

2. Useless content is being appended to the search results.
3. Initial search data, or random pages are not show outright when opening the search.

2023-04-11 13:01 UTC, Stuyk commented
I'm not sure we need pursue this offline search functionality any further after Vitepress finally added offline search with minisearch.

You can see the merged PR here: https://github.com/vuejs/vitepress/pull/2110

This repository is likely going to get archived after this.

2023-04-11 13:01 UTC, closed without merging